"""
handle_init
===========
CLI handler for the ``codex-django init <name>`` command.

Scaffolds a new Django project into ./src/<name>/:

  src/<name>/
    manage.py
    core/             - settings, urls, wsgi, asgi, redis, sitemaps
    system/           - SiteSettings, SEO, notifications, management commands
    cabinet/          - user dashboard skeleton (theme.css only)
    features/
      main/           - home & contacts views
    templates/        - base.html, includes/, main/, errors/
    static/
      css/            - @import chain + compiler_config.json
      css/cabinet/    - theme.css (white-labeling overrides)
      js/vendor/      - HTMX 2.x, Alpine.js placeholders
      js/app/         - main.js

Usage::

    codex-django init myproject
    codex-django init myproject --dir sandbox   # custom output path
    # or via interactive menu: codex-django -> Init new project
"""

from __future__ import annotations

import os
from pathlib import Path

from rich.console import Console

console = Console()


def _normalize_languages(languages: list[str] | None) -> list[str]:
    """Normalize language codes while preserving the declared order."""
    if not languages:
        return ["en"]

    normalized: list[str] = []
    for item in languages:
        code = item.strip().lower().replace("_", "-")
        if code and code not in normalized:
            normalized.append(code)
    return normalized or ["en"]


def _write_project_env(
    project_root: str, project_name: str, *, overwrite: bool, secret_key: str, field_encryption_key: str
) -> None:
    """Create a real local .env file for the generated project."""
    env_path = Path(project_root) / ".env"
    if env_path.exists() and not overwrite:
        return

    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_content = (
        f"# Project: {project_name}\n"
        "# Generated by codex-django\n\n"
        "# Security\n"
        f"SECRET_KEY={secret_key}\n"
        "DEBUG=True\n"
        "# Fernet-compatible key used by encrypted model fields\n"
        f"FIELD_ENCRYPTION_KEY={field_encryption_key}\n\n"
        "# Application\n"
        "ALLOWED_HOSTS=localhost,127.0.0.1\n"
        "SITE_BASE_URL=http://127.0.0.1:8000/\n\n"
        "# Database\n"
        f"# DATABASE_URL=postgres://user:pass@localhost:5432/{project_name}  # pragma: allowlist secret\n"
    )
    env_path.write_text(env_content, encoding="utf-8")


def handle_init(
    name: str,
    base_dir: str,
    target_dir: str | None = None,
    code_only: bool = False,
    dev_mode: bool = False,
    overwrite: bool = False,
    enable_i18n: bool = False,
    languages: list[str] | None = None,
    with_cabinet: bool = False,
    with_booking: bool = False,
) -> None:
    """Scaffold a new codex-django project.

    Args:
        name: Project package name.
        base_dir: Base directory used when no explicit target is provided.
        target_dir: Optional explicit project root output directory.
        code_only: Whether to omit repository wrapper files.
        dev_mode: Whether to scaffold into the library sandbox for local development.
        overwrite: Whether existing files may be replaced.
        enable_i18n: Whether i18n / modular locale support should be enabled.
        languages: Optional explicit list of language codes.
        with_cabinet: Whether cabinet support should be included.
        with_booking: Whether booking support should be included.
    """
    from codex_django_cli.engine import CLIEngine
    from codex_django_cli.utils import generate_field_encryption_key, generate_secret_key

    if dev_mode:
        lib_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
        pyproject_path = os.path.join(lib_root, "pyproject.toml")
        is_lib_source = False
        if os.path.exists(pyproject_path):
            with open(pyproject_path, encoding="utf-8") as f:
                if 'name = "codex-django"' in f.read() or 'name = "codex-django-cli"' in f.read():
                    is_lib_source = True

        if not is_lib_source:
            console.print("[red]❌ --dev mode is only available when running from the library's source.[/red]")
            return

        project_root = os.path.join(lib_root, "sandbox")
        backend_dir = os.path.join(project_root, "src", name)
    elif target_dir:
        project_root = os.path.abspath(target_dir)
        backend_dir = os.path.join(project_root, "src", name)
    else:
        project_root = os.path.join(base_dir, name)
        backend_dir = os.path.join(project_root, "src", name)

    if os.path.exists(os.path.join(backend_dir, "manage.py")) and not overwrite:
        console.print(f"[yellow]⚠ Django project already exists in:[/yellow] [bold]{backend_dir}[/bold]")
        console.print("[yellow]  Use --overwrite to re-scaffold.[/yellow]")
        return

    explicit_languages = languages is not None
    languages = _normalize_languages(languages)

    if enable_i18n or explicit_languages:
        enable_i18n = True

    secret_key = generate_secret_key()
    field_encryption_key = generate_field_encryption_key()

    engine = CLIEngine()
    context = {
        "project_name": name,
        "secret_key": secret_key,
        "enable_i18n": enable_i18n,
        "languages": languages,
        "with_cabinet": with_cabinet,
        "with_booking": with_booking,
    }

    if not code_only:
        engine.scaffold("repo", target_dir=project_root, context=context, overwrite=overwrite)
        deploy_dir = os.path.join(project_root, "deploy")
        engine.scaffold("deploy/shared", target_dir=deploy_dir, context=context, overwrite=overwrite)
        _write_project_env(
            project_root,
            name,
            overwrite=overwrite,
            secret_key=secret_key,
            field_encryption_key=field_encryption_key,
        )

    engine.scaffold("project", target_dir=backend_dir, context=context, overwrite=overwrite)

    if with_cabinet:
        engine.scaffold("features/client_cabinet", target_dir=backend_dir, context=context)
        console.print("[green]  ✓[/green] Client Cabinet scaffolded")

    if with_booking:
        engine.scaffold("features/booking", target_dir=backend_dir, context=context)
        console.print("[green]  ✓[/green] Booking (Advanced) scaffolded")

    # Notifications are part of the base system layer for every project.
    engine.scaffold(
        "features/notifications/feature/models",
        target_dir=os.path.join(backend_dir, "system", "models"),
        context={**context, "app_name": "system"},
    )
    engine.scaffold(
        "features/notifications/feature/selectors",
        target_dir=os.path.join(backend_dir, "system", "selectors"),
        context={**context, "app_name": "system"},
    )
    engine.scaffold(
        "features/notifications/feature/services",
        target_dir=os.path.join(backend_dir, "system", "services"),
        context={**context, "app_name": "system"},
    )
    engine.scaffold(
        "features/notifications/arq",
        target_dir=os.path.join(backend_dir, "core", "arq"),
        context={**context, "app_name": "system"},
    )
    console.print("[green]  ✓[/green] Notifications scaffolded into [bold]system/ + core/arq/[/bold]")

    console.print()
    if dev_mode:
        console.print(f"[green]✓[/green] [bold]DEV MODE:[/bold] Scaffolded into [bold]{project_root}[/bold]")
    elif code_only:
        console.print(f"[green]✓[/green] Core code [bold]{name}[/bold] injected into [bold]{backend_dir}[/bold]")
    else:
        modules = ["base project", "notifications"]
        if with_cabinet:
            modules.append("cabinet")
        if with_booking:
            modules.append("booking")
        console.print(f"[green]✓[/green] Project [bold]{name}[/bold] initialized in [bold]{project_root}[/bold]")
        console.print(f"  Modules: [cyan]{', '.join(modules)}[/cyan]")
        if enable_i18n:
            console.print(
                "  [dim]i18n is enabled; even a single selected language uses translation-aware settings.[/dim]"
            )

    console.print()
    if not code_only and not dev_mode:
        console.print(
            "[dim]Optional: run [cyan]codex-django[/cyan] -> "
            "[cyan]Deployment Setup[/cyan] later if you want Docker or CI/CD scaffolding.[/dim]"
        )
    console.print()
    console.print("[bold]Next steps for your new project:[/bold]")

    step = 1
    curr_dir_abs = os.path.abspath(os.getcwd())
    proj_root_abs = os.path.abspath(project_root)

    if not dev_mode and proj_root_abs != curr_dir_abs:
        console.print(f"  {step}. [cyan]Open the project folder: cd {os.path.basename(proj_root_abs)}[/cyan]")
        step += 1

    if not code_only and not dev_mode:
        console.print(f"  {step}. [cyan]Create a virtual environment for this project: python -m venv .venv[/cyan]")
        step += 1
        console.print(
            f"  {step}. [cyan]Activate it:[/cyan] source .venv/bin/activate [dim](Linux/macOS)[/dim] "
            f"or [cyan].venv\\Scripts\\activate[/cyan] [dim](Windows)[/dim]"
        )
        step += 1
        console.print(f"  {step}. [cyan]Install this project's dependencies: pip install -e .[/cyan]")
        step += 1
        console.print(
            f"  {step}. [cyan]Review the generated .env file and adjust values like "
            "ALLOWED_HOSTS or DATABASE_URL if needed.[/cyan]"
        )
        step += 1

    if not dev_mode:
        target = project_root if proj_root_abs != curr_dir_abs else "."
        manage_py_rel = os.path.relpath(os.path.join(backend_dir, "manage.py"), target)
        console.print(f"  {step}. [cyan]Apply database migrations: python {manage_py_rel} migrate[/cyan]")
        step += 1
        console.print(f"  {step}. [cyan]Start the development server: python {manage_py_rel} runserver[/cyan]")
    else:
        console.print(f"  {step}. Review the scaffolded files in [bold]sandbox/[/bold] or run the test suite there.")
